### ISSUE TITLE
Client-Side crash when selecting an empty slot (1.9)

### ISSUE THREAD

**Issue by kwpugh** [61352151511/Durability-Show#1]
When I switch to an empty slot on the inventory bar, the client crashes.

Crash report:  http://pastebin.com/raw/FdvPSjMq

**Comment by 61352151511** [comment]
Will be fixed in the next release (within 24 hours) thank you for the report. Reading the crash report it seems like it would occur when the main hand has an item that is not damageable and the off hand is empty. Not sure if that's the case but I'll work on a fix soon.
