### ISSUE TITLE
[1.11] random crash in SMP

### ISSUE THREAD

**Issue by Cat-McCatface** [61352151511/Durability-Show#6]
was doing fine until was wasting time then caused mc client to crash. wouldn't allow logging on to server until mod was removed

forge: 2053
Durability-Show: 4.0.0
log: [crash-2016-11-19_21.09.52-client.txt](https://github.com/61352151511/Durability-Show/files/601839/crash-2016-11-19_21.09.52-client.txt)

**Comment by 61352151511** [comment]
Try 4.0.1

**Comment by 61352151511** [comment]
If no feedback is given in 10 days this issue will be considered closed.
