### ISSUE TITLE
How do I move the statusbar? And add an in-game menu?

### ISSUE THREAD

**Issue by NovaViper** [61352151511/Durability-Show#8]
I have subtitles on in 1.11.2 but with that one, it blocks the durability status since the subtitles are at the bottom right. Is there a way to move it over? 

Also.. could you add a way to do this via in-game configuration menu using Forge's fully implemented configuration system? If you need help with that you can look at my mods, [ZeroQuest](https://github.com/NovaViper/ZeroQuest) and [TetraCraft](https://github.com/NovaViper/TetraCraft)

**Comment by 61352151511** [comment]
I'm currently on vacation so I will fix this when I'm back (Saturday). I thought I had the in game configuration setup but I'm probably wrong and forgot something.

**Comment by NovaViper** [comment]
Alrighty! Have a good vacation! I can actually commit a pull request to it later on today. I have done the in game configurations many times before ^^

**Comment by 61352151511** [comment]
I'm actually slightly confused about the in-game configuration. See src/main/java/com/sixonethree/durabilityshow/clientgui ModGuiConfig.java and GuiFactory.java I remember using the in game configuration last time I updated the mod. Perhaps some things changed in forge, I don't know. I can take a look at it after.

**Comment by NovaViper** [comment]
You should look at TetraCraft specifically.. it as updated for 1.10.2 and [Doggy Talents](https://github.com/ProPercivalalb/DoggyTalents) (I actually added in the in game configuration for this mod). Both feature in-game configurations that I implemented through Forge's system. I even went and added in a custom organization code inside the configurations.

**Comment by NovaViper** [comment]
Here's a [pull request](https://github.com/ProPercivalalb/DoggyTalents/pull/22) I made for Doggy Talents with the config gui and the custom organization code

**Comment by 61352151511** [comment]
I'm not too concerned about the organization just that the option to configure in-game is there. Looking at my code vs the PR code everything looks like it's already present. I may be missing something and if I am feel free to just point it out, can either just type it in the issue or make a PR, however I don't see what's missing and I can't test it myself and look more closely for a few days.

**Comment by NovaViper** [comment]
I'll go later on today and fix up the code for ya

**Comment by NovaViper** [comment]
Hey I started playing around, figuring out why the configuration menu wasn't coming up. I found that it was something the way your mcmod.info file was set up, how I fixed it was simply copied the example mcmod.info file and just moved the information from your mod into it.

**Comment by NovaViper** [comment]
Just created pull request GH-9, your welcome 👍

**Comment by 61352151511** [comment]
Fixed this issue with 4.1.1, if the corner is set to bottom right and subtitles are active, it renders on the left until there are no subtitles to show and then it goes back to the right. See the comment on #9 please.
